# Copyright 2022 Innkeeper tsai <mengjietsai@163.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/tsai/miniblog.

swagger: "2.0"
servers:
  - url: http://127.0.0.1:8080/v1
    description: development server
info:
  version: "1.0.0"
  title: miniblog api definition
  description: The API for the miniblog project
  contact:
    name: tsai
    email: mengjietsai@163.com
    url: https://github.com/tsai
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
